# Generated by Django 3.2.3 on 2021-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('finish_date', models.DateField()),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['user', 'finish_date'],
                'unique_together': {('task', 'user', 'finish_date')},
            },
        ),
    ]
